# vim:fileencoding=utf-8:foldmethod=marker

enable_audio_bell no

# Window decorations
hide_window_decorations yes
window_margin_width 12

#: Fonts {{{

font_family      IosevkaTerm Nerd Font Mono
font_size 14.0

#: The foreground and background colors.

background_opacity 0.95
# background_blur 0

## name: Kanagawa
## license: MIT
## author: Tommaso Laurenzi
## upstream: https://github.com/rebelot/kanagawa.nvim/

background #0d0c0c
foreground #DCD7BA
selection_background #2D4F67
selection_foreground #C8C093
url_color #72A7BC
cursor #C8C093

# Tabs
active_tab_background #1F1F28
active_tab_foreground #C8C093
inactive_tab_background  #1F1F28
inactive_tab_foreground #727169
#tab_bar_background #15161E

# normal
color0 #16161D
color1 #C34043
color2 #76946A
color3 #C0A36E
color4 #7E9CD8
color5 #957FB8
color6 #6A9589
color7 #C8C093

# bright
color8  #727169
color9  #E82424
color10 #98BB6C
color11 #E6C384
color12 #7FB4CA
color13 #938AA9
color14 #7AA89F
color15 #DCD7BA

# extended colors
color16 #FFA066
color17 #FF5D62
  
# make option key work for alt-f / alt-b
macos_option_as_alt yes

# Other configurations
cursor_shape beam
cursor_beam_thickness 1.8

mouse_hide_wait 3.0
detect_urls yes

repaint_delay 10
input_delay 3
sync_to_monitor yes

url_color #61afef

url_style curly

shell zsh
