# Disabled Audio Bell
enable_audio_bell no

# Color Configuration
include color.ini

# Window decorations
hide_window_decorations yes
window_padding_width 15

# Font Configuration
font_family      IosevkaTerm Nerd Font Mono
font_size 14.0
disable_ligatures never

# Cursor Configurations
cursor_shape beam
cursor_beam_thickness 1.8

# Urls Configurations
detect_urls yes
url_color #61afef
url_style curly

# Shell Configuration
shell zsh
