git:
    paging:
        colorArg: never
        pager: delta --dark --paging=never
        useConfig: false

customCommands:
    - key: 'C'
      command: 'git cz'
      description: 'commit with commitizen'
      context: 'files'
      loadingText: 'opening commitizen commit tool'
      subprocess: true
